codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 90%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
