name: Bug
description: Reportar un bug o problema
title: "[Bug]: "
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Reporte de Bug
        Por favor proporciona toda la información posible para reproducir el problema.

  - type: textarea
    id: description
    attributes:
      label: Descripción del Bug
      description: Describe claramente el problema
      placeholder: "Cuando hago X, ocurre Y en lugar de Z"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para Reproducir
      description: Pasos detallados para reproducir el bug
      placeholder: |
        1. Ir a '...'
        2. Click en '...'
        3. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento Esperado
      description: ¿Qué debería ocurrir?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento Actual
      description: ¿Qué está ocurriendo?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Componente Afectado
      options:
        - Dashboard
        - Lecciones
        - Quiz
        - Mini-juegos
        - Gamificación (XP/Badges)
        - Navegación
        - Storage/Persistencia
        - Otro
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severidad
      options:
        - critical (app no funciona)
        - high (feature principal rota)
        - medium (feature secundaria afectada)
        - low (problema menor/visual)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Entorno
      description: Browser, OS, etc.
      placeholder: |
        - Browser: Chrome 120
        - OS: macOS 14
        - Viewport: 1920x1080

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Logs
      description: Agrega screenshots o logs de consola si aplica
