export { useLocalStorage } from './useLocalStorage'
export { useXP, XP_REWARDS } from './useXP'
export { useProgress } from './useProgress'
export { useStreak } from './useStreak'
export { useBadges } from './useBadges'
export { usePageTracking } from './usePageTracking'
export { useQuizSearch, highlightText } from './useQuizSearch'
export type { QuizSearchResult, MatchLocation, UseQuizSearchReturn } from './useQuizSearch'
export { useKeyboardShortcut, useEscapeKey, useSearchShortcut } from './useKeyboardShortcut'
